replicaCount: 1

image:
  repository: ghcr.io/strrl/goat-on-kube/goat-exporter
  pullPolicy: IfNotPresent
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

secret:
  goatRpcNode: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: goat-exporter.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceMonitor:
  enabled: false
  interval: 15s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector: {}
tolerations: []
affinity: {}
