apiVersion: v1
kind: Service
metadata:
  name: {{ include "goat.fullname" . }}
  labels:
    {{- include "goat.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: http
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: ws
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
    - port: 1317
      targetPort: 1317
      protocol: TCP
      name: api
  selector:
    {{- include "goat.selectorLabels" . | nindent 4 }}
